### ISSUE TITLE
pop-up does not show (though shortcut seems to be registered)

### ISSUE THREAD

**Issue by afmoene** [kewisch/quickmove-extension#138]
Thanks for this great add-on. When I access it from the button on the toolbar it works perfect.

But the pop-up does not launch. I use the standard short-cut, and it seems to register.

In the Developer Tools console window I saw the following messages appear after hitting the Ctrl-Shift-N shortcut. 

Error (red)
FrameData missing for quickmove@mozilla.kewis.ch page moz-extension://0f7d0801-cf68-4754-b75f-f57a8391adb9/popup/popup.html?action=move&allowed=move,copy,tag,goto [ExtensionPageChild.sys.mjs:443](resource://gre/modules/ExtensionPageChild.sys.mjs)
    initExtensionContext resource://gre/modules/ExtensionPageChild.sys.mjs:443
    initExtensionContext chrome://messenger/content/processScript.js:56
    initExtensionDocument resource://gre/modules/ExtensionProcessScript.sys.mjs:374

Warning (yellow)
Loading failed for the module with source “moz-extension://0f7d0801-cf68-4754-b75f-f57a8391adb9/popup/baseItemList.js”. 
[popup.html:11:46](moz-extension://0f7d0801-cf68-4754-b75f-f57a8391adb9/popup/popup.html?action=move&allowed=move,copy,tag,goto)

![Knipsel](https://github.com/kewisch/quickmove-extension/assets/11646435/3d483c26-69a8-400e-957e-0da07aba92ef)

​Context: Windows 10, Thunderbird 115.5.0 (64-bit), Quick Folder Move 2.7.0

**Comment by kewisch** [comment]
Hmm. Can you try uninstalling and re-installing the add-on? I'm not really sure how to solve the first error message, this error is from somewhere within the Thunderbird/Firefox extensions code. The second error sounds like filename case-sensitivity that I thought I had fixed with 2.7.0

**Comment by scientific-method-course** [comment]
Just unistalling and installing the add-on did not work. But when I disabled all other add-ons, it worked. Subsequently, I enabled my other add-ons one-by-one. And then the QuickMove add-on kept on working. It's unclear to me how this would work, but apparently there is some interaction between the add-ons that depends on the order in which they have been installed/enabled.
For me the issue has been solved now.

**Comment by kewisch** [comment]
Can you try 2.8.1 maybe? It will be reviewed and released shortly, otherwise you can grab the .xpi file from the github release.

**Comment by scientific-method-course** [comment]
Indeed, it seems to work in a stable way now. Thanks!

**Comment by scientific-method-course** [comment]
Update on this closed issue: the issue is still there but I've narrowed it down a bit:

The issue (popup not showing) only occurs when I have the Compact Headers extension enabled (https://addons.thunderbird.net/en-US/thunderbird/addon/compact-headers/)
More specifically: 
- when I have the headers collapsed, the pop-up does _not_ show
- when I have the headers not collapsed, the pop-up _does_ show

I have no programming experience with Thunderbird extensions, so I have no idea how the two would interact. Nor, which of the two extensions would be the cause of this unintended interaction. Hence, I do not know wha twould be the way forward. 

3.
